//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  corsi: Corsi;
  corsiConnection: CorsiConnection;
  contatti: Contatti;
  contattiConnection: ContattiConnection;
  docenti: Docenti;
  docentiConnection: DocentiConnection;
  presidenza: Presidenza;
  presidenzaConnection: PresidenzaConnection;
  mission: Mission;
  missionConnection: MissionConnection;
  soci: Soci;
  sociConnection: SociConnection;
  documenti: Documenti;
  documentiConnection: DocumentiConnection;
  chiSiamo: ChiSiamo;
  chiSiamoConnection: ChiSiamoConnection;
  eventi: Eventi;
  eventiConnection: EventiConnection;
  premio: Premio;
  premioConnection: PremioConnection;
  testiVari: TestiVari;
  testiVariConnection: TestiVariConnection;
  galleria: Galleria;
  galleriaConnection: GalleriaConnection;
  header: Header;
  headerConnection: HeaderConnection;
  iniziative: Iniziative;
  iniziativeConnection: IniziativeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCorsiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCorsiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CorsiFilter>;
};


export type QueryContattiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContattiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContattiFilter>;
};


export type QueryDocentiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocentiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocentiFilter>;
};


export type QueryPresidenzaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPresidenzaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PresidenzaFilter>;
};


export type QueryMissionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMissionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MissionFilter>;
};


export type QuerySociArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySociConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SociFilter>;
};


export type QueryDocumentiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentiFilter>;
};


export type QueryChiSiamoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryChiSiamoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ChiSiamoFilter>;
};


export type QueryEventiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventiFilter>;
};


export type QueryPremioArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPremioConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PremioFilter>;
};


export type QueryTestiVariArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestiVariConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestiVariFilter>;
};


export type QueryGalleriaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleriaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleriaFilter>;
};


export type QueryHeaderArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeaderConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeaderFilter>;
};


export type QueryIniziativeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIniziativeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IniziativeFilter>;
};

export type DocumentFilter = {
  corsi?: InputMaybe<CorsiFilter>;
  contatti?: InputMaybe<ContattiFilter>;
  docenti?: InputMaybe<DocentiFilter>;
  presidenza?: InputMaybe<PresidenzaFilter>;
  mission?: InputMaybe<MissionFilter>;
  soci?: InputMaybe<SociFilter>;
  documenti?: InputMaybe<DocumentiFilter>;
  chiSiamo?: InputMaybe<ChiSiamoFilter>;
  eventi?: InputMaybe<EventiFilter>;
  premio?: InputMaybe<PremioFilter>;
  testiVari?: InputMaybe<TestiVariFilter>;
  galleria?: InputMaybe<GalleriaFilter>;
  header?: InputMaybe<HeaderFilter>;
  iniziative?: InputMaybe<IniziativeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Corsi | Contatti | Docenti | Presidenza | Mission | Soci | Documenti | ChiSiamo | Eventi | Premio | TestiVari | Galleria | Header | Iniziative | Folder;

export type CorsiElenco = {
  __typename?: 'CorsiElenco';
  nome?: Maybe<Scalars['String']['output']>;
};

export type Corsi = Node & Document & {
  __typename?: 'Corsi';
  titolo?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  elenco?: Maybe<Array<Maybe<CorsiElenco>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type CorsiElencoFilter = {
  nome?: InputMaybe<StringFilter>;
};

export type CorsiFilter = {
  titolo?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  elenco?: InputMaybe<CorsiElencoFilter>;
};

export type CorsiConnectionEdges = {
  __typename?: 'CorsiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Corsi>;
};

export type CorsiConnection = Connection & {
  __typename?: 'CorsiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CorsiConnectionEdges>>>;
};

export type Contatti = Node & Document & {
  __typename?: 'Contatti';
  indirizzo?: Maybe<Scalars['String']['output']>;
  telefono?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  piva?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  tiktok?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContattiFilter = {
  indirizzo?: InputMaybe<StringFilter>;
  telefono?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  piva?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  tiktok?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
};

export type ContattiConnectionEdges = {
  __typename?: 'ContattiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contatti>;
};

export type ContattiConnection = Connection & {
  __typename?: 'ContattiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContattiConnectionEdges>>>;
};

export type DocentiElenco = {
  __typename?: 'DocentiElenco';
  nome?: Maybe<Scalars['String']['output']>;
  ruolo?: Maybe<Scalars['String']['output']>;
  cv?: Maybe<Scalars['String']['output']>;
};

export type Docenti = Node & Document & {
  __typename?: 'Docenti';
  elenco?: Maybe<Array<Maybe<DocentiElenco>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DocentiElencoFilter = {
  nome?: InputMaybe<StringFilter>;
  ruolo?: InputMaybe<StringFilter>;
  cv?: InputMaybe<StringFilter>;
};

export type DocentiFilter = {
  elenco?: InputMaybe<DocentiElencoFilter>;
};

export type DocentiConnectionEdges = {
  __typename?: 'DocentiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Docenti>;
};

export type DocentiConnection = Connection & {
  __typename?: 'DocentiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocentiConnectionEdges>>>;
};

export type Presidenza = Node & Document & {
  __typename?: 'Presidenza';
  nome?: Maybe<Scalars['String']['output']>;
  ruolo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PresidenzaFilter = {
  nome?: InputMaybe<StringFilter>;
  ruolo?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type PresidenzaConnectionEdges = {
  __typename?: 'PresidenzaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Presidenza>;
};

export type PresidenzaConnection = Connection & {
  __typename?: 'PresidenzaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PresidenzaConnectionEdges>>>;
};

export type Mission = Node & Document & {
  __typename?: 'Mission';
  citazione?: Maybe<Scalars['String']['output']>;
  testo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MissionFilter = {
  citazione?: InputMaybe<StringFilter>;
  testo?: InputMaybe<StringFilter>;
};

export type MissionConnectionEdges = {
  __typename?: 'MissionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Mission>;
};

export type MissionConnection = Connection & {
  __typename?: 'MissionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MissionConnectionEdges>>>;
};

export type Soci = Node & Document & {
  __typename?: 'Soci';
  testo?: Maybe<Scalars['String']['output']>;
  tesseraTitolo?: Maybe<Scalars['String']['output']>;
  tesseraPrezzo?: Maybe<Scalars['String']['output']>;
  tesseraTesto?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SociFilter = {
  testo?: InputMaybe<StringFilter>;
  tesseraTitolo?: InputMaybe<StringFilter>;
  tesseraPrezzo?: InputMaybe<StringFilter>;
  tesseraTesto?: InputMaybe<StringFilter>;
};

export type SociConnectionEdges = {
  __typename?: 'SociConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Soci>;
};

export type SociConnection = Connection & {
  __typename?: 'SociConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SociConnectionEdges>>>;
};

export type Documenti = Node & Document & {
  __typename?: 'Documenti';
  statuto?: Maybe<Scalars['String']['output']>;
  regolamento?: Maybe<Scalars['String']['output']>;
  modulo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DocumentiFilter = {
  statuto?: InputMaybe<ImageFilter>;
  regolamento?: InputMaybe<ImageFilter>;
  modulo?: InputMaybe<ImageFilter>;
};

export type DocumentiConnectionEdges = {
  __typename?: 'DocumentiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Documenti>;
};

export type DocumentiConnection = Connection & {
  __typename?: 'DocumentiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentiConnectionEdges>>>;
};

export type ChiSiamoStats = {
  __typename?: 'ChiSiamoStats';
  numero?: Maybe<Scalars['String']['output']>;
  etichetta?: Maybe<Scalars['String']['output']>;
};

export type ChiSiamo = Node & Document & {
  __typename?: 'ChiSiamo';
  titolo?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<ChiSiamoStats>>>;
  testo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ChiSiamoStatsFilter = {
  numero?: InputMaybe<StringFilter>;
  etichetta?: InputMaybe<StringFilter>;
};

export type ChiSiamoFilter = {
  titolo?: InputMaybe<StringFilter>;
  stats?: InputMaybe<ChiSiamoStatsFilter>;
  testo?: InputMaybe<StringFilter>;
};

export type ChiSiamoConnectionEdges = {
  __typename?: 'ChiSiamoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ChiSiamo>;
};

export type ChiSiamoConnection = Connection & {
  __typename?: 'ChiSiamoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ChiSiamoConnectionEdges>>>;
};

export type EventiElenco = {
  __typename?: 'EventiElenco';
  titolo?: Maybe<Scalars['String']['output']>;
  testo?: Maybe<Scalars['String']['output']>;
};

export type Eventi = Node & Document & {
  __typename?: 'Eventi';
  elenco?: Maybe<Array<Maybe<EventiElenco>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventiElencoFilter = {
  titolo?: InputMaybe<StringFilter>;
  testo?: InputMaybe<StringFilter>;
};

export type EventiFilter = {
  elenco?: InputMaybe<EventiElencoFilter>;
};

export type EventiConnectionEdges = {
  __typename?: 'EventiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Eventi>;
};

export type EventiConnection = Connection & {
  __typename?: 'EventiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventiConnectionEdges>>>;
};

export type PremioAlboOro = {
  __typename?: 'PremioAlboOro';
  nome?: Maybe<Scalars['String']['output']>;
};

export type Premio = Node & Document & {
  __typename?: 'Premio';
  testo?: Maybe<Scalars['String']['output']>;
  alboOro?: Maybe<Array<Maybe<PremioAlboOro>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PremioAlboOroFilter = {
  nome?: InputMaybe<StringFilter>;
};

export type PremioFilter = {
  testo?: InputMaybe<StringFilter>;
  alboOro?: InputMaybe<PremioAlboOroFilter>;
};

export type PremioConnectionEdges = {
  __typename?: 'PremioConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Premio>;
};

export type PremioConnection = Connection & {
  __typename?: 'PremioConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PremioConnectionEdges>>>;
};

export type TestiVari = Node & Document & {
  __typename?: 'TestiVari';
  candidatureTitolo?: Maybe<Scalars['String']['output']>;
  candidatureTesto?: Maybe<Scalars['String']['output']>;
  trasparenzaTesto?: Maybe<Scalars['String']['output']>;
  footerDescrizione?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestiVariFilter = {
  candidatureTitolo?: InputMaybe<StringFilter>;
  candidatureTesto?: InputMaybe<StringFilter>;
  trasparenzaTesto?: InputMaybe<StringFilter>;
  footerDescrizione?: InputMaybe<StringFilter>;
};

export type TestiVariConnectionEdges = {
  __typename?: 'TestiVariConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TestiVari>;
};

export type TestiVariConnection = Connection & {
  __typename?: 'TestiVariConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestiVariConnectionEdges>>>;
};

export type GalleriaImmagini = {
  __typename?: 'GalleriaImmagini';
  url?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Galleria = Node & Document & {
  __typename?: 'Galleria';
  immagini?: Maybe<Array<Maybe<GalleriaImmagini>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleriaImmaginiFilter = {
  url?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type GalleriaFilter = {
  immagini?: InputMaybe<GalleriaImmaginiFilter>;
};

export type GalleriaConnectionEdges = {
  __typename?: 'GalleriaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Galleria>;
};

export type GalleriaConnection = Connection & {
  __typename?: 'GalleriaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleriaConnectionEdges>>>;
};

export type Header = Node & Document & {
  __typename?: 'Header';
  logoMain?: Maybe<Scalars['String']['output']>;
  logoSub?: Maybe<Scalars['String']['output']>;
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroTitolo?: Maybe<Scalars['String']['output']>;
  heroSottotitolo?: Maybe<Scalars['String']['output']>;
  heroDescrizione?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HeaderFilter = {
  logoMain?: InputMaybe<StringFilter>;
  logoSub?: InputMaybe<StringFilter>;
  heroEyebrow?: InputMaybe<StringFilter>;
  heroTitolo?: InputMaybe<StringFilter>;
  heroSottotitolo?: InputMaybe<StringFilter>;
  heroDescrizione?: InputMaybe<StringFilter>;
};

export type HeaderConnectionEdges = {
  __typename?: 'HeaderConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Header>;
};

export type HeaderConnection = Connection & {
  __typename?: 'HeaderConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeaderConnectionEdges>>>;
};

export type IniziativeElenco = {
  __typename?: 'IniziativeElenco';
  testo?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
};

export type Iniziative = Node & Document & {
  __typename?: 'Iniziative';
  elenco?: Maybe<Array<Maybe<IniziativeElenco>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type IniziativeElencoFilter = {
  testo?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
};

export type IniziativeFilter = {
  elenco?: InputMaybe<IniziativeElencoFilter>;
};

export type IniziativeConnectionEdges = {
  __typename?: 'IniziativeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Iniziative>;
};

export type IniziativeConnection = Connection & {
  __typename?: 'IniziativeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IniziativeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateCorsi: Corsi;
  createCorsi: Corsi;
  updateContatti: Contatti;
  createContatti: Contatti;
  updateDocenti: Docenti;
  createDocenti: Docenti;
  updatePresidenza: Presidenza;
  createPresidenza: Presidenza;
  updateMission: Mission;
  createMission: Mission;
  updateSoci: Soci;
  createSoci: Soci;
  updateDocumenti: Documenti;
  createDocumenti: Documenti;
  updateChiSiamo: ChiSiamo;
  createChiSiamo: ChiSiamo;
  updateEventi: Eventi;
  createEventi: Eventi;
  updatePremio: Premio;
  createPremio: Premio;
  updateTestiVari: TestiVari;
  createTestiVari: TestiVari;
  updateGalleria: Galleria;
  createGalleria: Galleria;
  updateHeader: Header;
  createHeader: Header;
  updateIniziative: Iniziative;
  createIniziative: Iniziative;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateCorsiArgs = {
  relativePath: Scalars['String']['input'];
  params: CorsiMutation;
};


export type MutationCreateCorsiArgs = {
  relativePath: Scalars['String']['input'];
  params: CorsiMutation;
};


export type MutationUpdateContattiArgs = {
  relativePath: Scalars['String']['input'];
  params: ContattiMutation;
};


export type MutationCreateContattiArgs = {
  relativePath: Scalars['String']['input'];
  params: ContattiMutation;
};


export type MutationUpdateDocentiArgs = {
  relativePath: Scalars['String']['input'];
  params: DocentiMutation;
};


export type MutationCreateDocentiArgs = {
  relativePath: Scalars['String']['input'];
  params: DocentiMutation;
};


export type MutationUpdatePresidenzaArgs = {
  relativePath: Scalars['String']['input'];
  params: PresidenzaMutation;
};


export type MutationCreatePresidenzaArgs = {
  relativePath: Scalars['String']['input'];
  params: PresidenzaMutation;
};


export type MutationUpdateMissionArgs = {
  relativePath: Scalars['String']['input'];
  params: MissionMutation;
};


export type MutationCreateMissionArgs = {
  relativePath: Scalars['String']['input'];
  params: MissionMutation;
};


export type MutationUpdateSociArgs = {
  relativePath: Scalars['String']['input'];
  params: SociMutation;
};


export type MutationCreateSociArgs = {
  relativePath: Scalars['String']['input'];
  params: SociMutation;
};


export type MutationUpdateDocumentiArgs = {
  relativePath: Scalars['String']['input'];
  params: DocumentiMutation;
};


export type MutationCreateDocumentiArgs = {
  relativePath: Scalars['String']['input'];
  params: DocumentiMutation;
};


export type MutationUpdateChiSiamoArgs = {
  relativePath: Scalars['String']['input'];
  params: ChiSiamoMutation;
};


export type MutationCreateChiSiamoArgs = {
  relativePath: Scalars['String']['input'];
  params: ChiSiamoMutation;
};


export type MutationUpdateEventiArgs = {
  relativePath: Scalars['String']['input'];
  params: EventiMutation;
};


export type MutationCreateEventiArgs = {
  relativePath: Scalars['String']['input'];
  params: EventiMutation;
};


export type MutationUpdatePremioArgs = {
  relativePath: Scalars['String']['input'];
  params: PremioMutation;
};


export type MutationCreatePremioArgs = {
  relativePath: Scalars['String']['input'];
  params: PremioMutation;
};


export type MutationUpdateTestiVariArgs = {
  relativePath: Scalars['String']['input'];
  params: TestiVariMutation;
};


export type MutationCreateTestiVariArgs = {
  relativePath: Scalars['String']['input'];
  params: TestiVariMutation;
};


export type MutationUpdateGalleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleriaMutation;
};


export type MutationCreateGalleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleriaMutation;
};


export type MutationUpdateHeaderArgs = {
  relativePath: Scalars['String']['input'];
  params: HeaderMutation;
};


export type MutationCreateHeaderArgs = {
  relativePath: Scalars['String']['input'];
  params: HeaderMutation;
};


export type MutationUpdateIniziativeArgs = {
  relativePath: Scalars['String']['input'];
  params: IniziativeMutation;
};


export type MutationCreateIniziativeArgs = {
  relativePath: Scalars['String']['input'];
  params: IniziativeMutation;
};

export type DocumentUpdateMutation = {
  corsi?: InputMaybe<CorsiMutation>;
  contatti?: InputMaybe<ContattiMutation>;
  docenti?: InputMaybe<DocentiMutation>;
  presidenza?: InputMaybe<PresidenzaMutation>;
  mission?: InputMaybe<MissionMutation>;
  soci?: InputMaybe<SociMutation>;
  documenti?: InputMaybe<DocumentiMutation>;
  chiSiamo?: InputMaybe<ChiSiamoMutation>;
  eventi?: InputMaybe<EventiMutation>;
  premio?: InputMaybe<PremioMutation>;
  testiVari?: InputMaybe<TestiVariMutation>;
  galleria?: InputMaybe<GalleriaMutation>;
  header?: InputMaybe<HeaderMutation>;
  iniziative?: InputMaybe<IniziativeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  corsi?: InputMaybe<CorsiMutation>;
  contatti?: InputMaybe<ContattiMutation>;
  docenti?: InputMaybe<DocentiMutation>;
  presidenza?: InputMaybe<PresidenzaMutation>;
  mission?: InputMaybe<MissionMutation>;
  soci?: InputMaybe<SociMutation>;
  documenti?: InputMaybe<DocumentiMutation>;
  chiSiamo?: InputMaybe<ChiSiamoMutation>;
  eventi?: InputMaybe<EventiMutation>;
  premio?: InputMaybe<PremioMutation>;
  testiVari?: InputMaybe<TestiVariMutation>;
  galleria?: InputMaybe<GalleriaMutation>;
  header?: InputMaybe<HeaderMutation>;
  iniziative?: InputMaybe<IniziativeMutation>;
};

export type CorsiElencoMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
};

export type CorsiMutation = {
  titolo?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  elenco?: InputMaybe<Array<InputMaybe<CorsiElencoMutation>>>;
};

export type ContattiMutation = {
  indirizzo?: InputMaybe<Scalars['String']['input']>;
  telefono?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  piva?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  tiktok?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
};

export type DocentiElencoMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
  ruolo?: InputMaybe<Scalars['String']['input']>;
  cv?: InputMaybe<Scalars['String']['input']>;
};

export type DocentiMutation = {
  elenco?: InputMaybe<Array<InputMaybe<DocentiElencoMutation>>>;
};

export type PresidenzaMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
  ruolo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type MissionMutation = {
  citazione?: InputMaybe<Scalars['String']['input']>;
  testo?: InputMaybe<Scalars['String']['input']>;
};

export type SociMutation = {
  testo?: InputMaybe<Scalars['String']['input']>;
  tesseraTitolo?: InputMaybe<Scalars['String']['input']>;
  tesseraPrezzo?: InputMaybe<Scalars['String']['input']>;
  tesseraTesto?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentiMutation = {
  statuto?: InputMaybe<Scalars['String']['input']>;
  regolamento?: InputMaybe<Scalars['String']['input']>;
  modulo?: InputMaybe<Scalars['String']['input']>;
};

export type ChiSiamoStatsMutation = {
  numero?: InputMaybe<Scalars['String']['input']>;
  etichetta?: InputMaybe<Scalars['String']['input']>;
};

export type ChiSiamoMutation = {
  titolo?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<ChiSiamoStatsMutation>>>;
  testo?: InputMaybe<Scalars['String']['input']>;
};

export type EventiElencoMutation = {
  titolo?: InputMaybe<Scalars['String']['input']>;
  testo?: InputMaybe<Scalars['String']['input']>;
};

export type EventiMutation = {
  elenco?: InputMaybe<Array<InputMaybe<EventiElencoMutation>>>;
};

export type PremioAlboOroMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
};

export type PremioMutation = {
  testo?: InputMaybe<Scalars['String']['input']>;
  alboOro?: InputMaybe<Array<InputMaybe<PremioAlboOroMutation>>>;
};

export type TestiVariMutation = {
  candidatureTitolo?: InputMaybe<Scalars['String']['input']>;
  candidatureTesto?: InputMaybe<Scalars['String']['input']>;
  trasparenzaTesto?: InputMaybe<Scalars['String']['input']>;
  footerDescrizione?: InputMaybe<Scalars['String']['input']>;
};

export type GalleriaImmaginiMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type GalleriaMutation = {
  immagini?: InputMaybe<Array<InputMaybe<GalleriaImmaginiMutation>>>;
};

export type HeaderMutation = {
  logoMain?: InputMaybe<Scalars['String']['input']>;
  logoSub?: InputMaybe<Scalars['String']['input']>;
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroTitolo?: InputMaybe<Scalars['String']['input']>;
  heroSottotitolo?: InputMaybe<Scalars['String']['input']>;
  heroDescrizione?: InputMaybe<Scalars['String']['input']>;
};

export type IniziativeElencoMutation = {
  testo?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
};

export type IniziativeMutation = {
  elenco?: InputMaybe<Array<InputMaybe<IniziativeElencoMutation>>>;
};

export type CorsiPartsFragment = { __typename: 'Corsi', titolo?: string | null, intro?: string | null, elenco?: Array<{ __typename: 'CorsiElenco', nome?: string | null } | null> | null };

export type ContattiPartsFragment = { __typename: 'Contatti', indirizzo?: string | null, telefono?: string | null, email?: string | null, piva?: string | null, facebook?: string | null, instagram?: string | null, tiktok?: string | null, whatsapp?: string | null };

export type DocentiPartsFragment = { __typename: 'Docenti', elenco?: Array<{ __typename: 'DocentiElenco', nome?: string | null, ruolo?: string | null, cv?: string | null } | null> | null };

export type PresidenzaPartsFragment = { __typename: 'Presidenza', nome?: string | null, ruolo?: string | null, bio?: string | null };

export type MissionPartsFragment = { __typename: 'Mission', citazione?: string | null, testo?: string | null };

export type SociPartsFragment = { __typename: 'Soci', testo?: string | null, tesseraTitolo?: string | null, tesseraPrezzo?: string | null, tesseraTesto?: string | null };

export type DocumentiPartsFragment = { __typename: 'Documenti', statuto?: string | null, regolamento?: string | null, modulo?: string | null };

export type ChiSiamoPartsFragment = { __typename: 'ChiSiamo', titolo?: string | null, testo?: string | null, stats?: Array<{ __typename: 'ChiSiamoStats', numero?: string | null, etichetta?: string | null } | null> | null };

export type EventiPartsFragment = { __typename: 'Eventi', elenco?: Array<{ __typename: 'EventiElenco', titolo?: string | null, testo?: string | null } | null> | null };

export type PremioPartsFragment = { __typename: 'Premio', testo?: string | null, alboOro?: Array<{ __typename: 'PremioAlboOro', nome?: string | null } | null> | null };

export type TestiVariPartsFragment = { __typename: 'TestiVari', candidatureTitolo?: string | null, candidatureTesto?: string | null, trasparenzaTesto?: string | null, footerDescrizione?: string | null };

export type GalleriaPartsFragment = { __typename: 'Galleria', immagini?: Array<{ __typename: 'GalleriaImmagini', url?: string | null, alt?: string | null } | null> | null };

export type HeaderPartsFragment = { __typename: 'Header', logoMain?: string | null, logoSub?: string | null, heroEyebrow?: string | null, heroTitolo?: string | null, heroSottotitolo?: string | null, heroDescrizione?: string | null };

export type IniziativePartsFragment = { __typename: 'Iniziative', elenco?: Array<{ __typename: 'IniziativeElenco', testo?: string | null, foto?: string | null } | null> | null };

export type CorsiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CorsiQuery = { __typename?: 'Query', corsi: { __typename: 'Corsi', id: string, titolo?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'CorsiElenco', nome?: string | null } | null> | null } };

export type CorsiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CorsiFilter>;
}>;


export type CorsiConnectionQuery = { __typename?: 'Query', corsiConnection: { __typename?: 'CorsiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CorsiConnectionEdges', cursor: string, node?: { __typename: 'Corsi', id: string, titolo?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'CorsiElenco', nome?: string | null } | null> | null } | null } | null> | null } };

export type ContattiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContattiQuery = { __typename?: 'Query', contatti: { __typename: 'Contatti', id: string, indirizzo?: string | null, telefono?: string | null, email?: string | null, piva?: string | null, facebook?: string | null, instagram?: string | null, tiktok?: string | null, whatsapp?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContattiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContattiFilter>;
}>;


export type ContattiConnectionQuery = { __typename?: 'Query', contattiConnection: { __typename?: 'ContattiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContattiConnectionEdges', cursor: string, node?: { __typename: 'Contatti', id: string, indirizzo?: string | null, telefono?: string | null, email?: string | null, piva?: string | null, facebook?: string | null, instagram?: string | null, tiktok?: string | null, whatsapp?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DocentiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DocentiQuery = { __typename?: 'Query', docenti: { __typename: 'Docenti', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'DocentiElenco', nome?: string | null, ruolo?: string | null, cv?: string | null } | null> | null } };

export type DocentiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocentiFilter>;
}>;


export type DocentiConnectionQuery = { __typename?: 'Query', docentiConnection: { __typename?: 'DocentiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DocentiConnectionEdges', cursor: string, node?: { __typename: 'Docenti', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'DocentiElenco', nome?: string | null, ruolo?: string | null, cv?: string | null } | null> | null } | null } | null> | null } };

export type PresidenzaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PresidenzaQuery = { __typename?: 'Query', presidenza: { __typename: 'Presidenza', id: string, nome?: string | null, ruolo?: string | null, bio?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PresidenzaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PresidenzaFilter>;
}>;


export type PresidenzaConnectionQuery = { __typename?: 'Query', presidenzaConnection: { __typename?: 'PresidenzaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PresidenzaConnectionEdges', cursor: string, node?: { __typename: 'Presidenza', id: string, nome?: string | null, ruolo?: string | null, bio?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MissionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MissionQuery = { __typename?: 'Query', mission: { __typename: 'Mission', id: string, citazione?: string | null, testo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MissionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MissionFilter>;
}>;


export type MissionConnectionQuery = { __typename?: 'Query', missionConnection: { __typename?: 'MissionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MissionConnectionEdges', cursor: string, node?: { __typename: 'Mission', id: string, citazione?: string | null, testo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SociQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SociQuery = { __typename?: 'Query', soci: { __typename: 'Soci', id: string, testo?: string | null, tesseraTitolo?: string | null, tesseraPrezzo?: string | null, tesseraTesto?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SociConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SociFilter>;
}>;


export type SociConnectionQuery = { __typename?: 'Query', sociConnection: { __typename?: 'SociConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SociConnectionEdges', cursor: string, node?: { __typename: 'Soci', id: string, testo?: string | null, tesseraTitolo?: string | null, tesseraPrezzo?: string | null, tesseraTesto?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DocumentiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DocumentiQuery = { __typename?: 'Query', documenti: { __typename: 'Documenti', id: string, statuto?: string | null, regolamento?: string | null, modulo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DocumentiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentiFilter>;
}>;


export type DocumentiConnectionQuery = { __typename?: 'Query', documentiConnection: { __typename?: 'DocumentiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DocumentiConnectionEdges', cursor: string, node?: { __typename: 'Documenti', id: string, statuto?: string | null, regolamento?: string | null, modulo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ChiSiamoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ChiSiamoQuery = { __typename?: 'Query', chiSiamo: { __typename: 'ChiSiamo', id: string, titolo?: string | null, testo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'ChiSiamoStats', numero?: string | null, etichetta?: string | null } | null> | null } };

export type ChiSiamoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ChiSiamoFilter>;
}>;


export type ChiSiamoConnectionQuery = { __typename?: 'Query', chiSiamoConnection: { __typename?: 'ChiSiamoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ChiSiamoConnectionEdges', cursor: string, node?: { __typename: 'ChiSiamo', id: string, titolo?: string | null, testo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'ChiSiamoStats', numero?: string | null, etichetta?: string | null } | null> | null } | null } | null> | null } };

export type EventiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventiQuery = { __typename?: 'Query', eventi: { __typename: 'Eventi', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'EventiElenco', titolo?: string | null, testo?: string | null } | null> | null } };

export type EventiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventiFilter>;
}>;


export type EventiConnectionQuery = { __typename?: 'Query', eventiConnection: { __typename?: 'EventiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventiConnectionEdges', cursor: string, node?: { __typename: 'Eventi', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'EventiElenco', titolo?: string | null, testo?: string | null } | null> | null } | null } | null> | null } };

export type PremioQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PremioQuery = { __typename?: 'Query', premio: { __typename: 'Premio', id: string, testo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, alboOro?: Array<{ __typename: 'PremioAlboOro', nome?: string | null } | null> | null } };

export type PremioConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PremioFilter>;
}>;


export type PremioConnectionQuery = { __typename?: 'Query', premioConnection: { __typename?: 'PremioConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PremioConnectionEdges', cursor: string, node?: { __typename: 'Premio', id: string, testo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, alboOro?: Array<{ __typename: 'PremioAlboOro', nome?: string | null } | null> | null } | null } | null> | null } };

export type TestiVariQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestiVariQuery = { __typename?: 'Query', testiVari: { __typename: 'TestiVari', id: string, candidatureTitolo?: string | null, candidatureTesto?: string | null, trasparenzaTesto?: string | null, footerDescrizione?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestiVariConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestiVariFilter>;
}>;


export type TestiVariConnectionQuery = { __typename?: 'Query', testiVariConnection: { __typename?: 'TestiVariConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestiVariConnectionEdges', cursor: string, node?: { __typename: 'TestiVari', id: string, candidatureTitolo?: string | null, candidatureTesto?: string | null, trasparenzaTesto?: string | null, footerDescrizione?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GalleriaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleriaQuery = { __typename?: 'Query', galleria: { __typename: 'Galleria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, immagini?: Array<{ __typename: 'GalleriaImmagini', url?: string | null, alt?: string | null } | null> | null } };

export type GalleriaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleriaFilter>;
}>;


export type GalleriaConnectionQuery = { __typename?: 'Query', galleriaConnection: { __typename?: 'GalleriaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleriaConnectionEdges', cursor: string, node?: { __typename: 'Galleria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, immagini?: Array<{ __typename: 'GalleriaImmagini', url?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export type HeaderQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeaderQuery = { __typename?: 'Query', header: { __typename: 'Header', id: string, logoMain?: string | null, logoSub?: string | null, heroEyebrow?: string | null, heroTitolo?: string | null, heroSottotitolo?: string | null, heroDescrizione?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HeaderConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeaderFilter>;
}>;


export type HeaderConnectionQuery = { __typename?: 'Query', headerConnection: { __typename?: 'HeaderConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeaderConnectionEdges', cursor: string, node?: { __typename: 'Header', id: string, logoMain?: string | null, logoSub?: string | null, heroEyebrow?: string | null, heroTitolo?: string | null, heroSottotitolo?: string | null, heroDescrizione?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type IniziativeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IniziativeQuery = { __typename?: 'Query', iniziative: { __typename: 'Iniziative', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'IniziativeElenco', testo?: string | null, foto?: string | null } | null> | null } };

export type IniziativeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IniziativeFilter>;
}>;


export type IniziativeConnectionQuery = { __typename?: 'Query', iniziativeConnection: { __typename?: 'IniziativeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IniziativeConnectionEdges', cursor: string, node?: { __typename: 'Iniziative', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, elenco?: Array<{ __typename: 'IniziativeElenco', testo?: string | null, foto?: string | null } | null> | null } | null } | null> | null } };

export const CorsiPartsFragmentDoc = gql`
    fragment CorsiParts on Corsi {
  __typename
  titolo
  intro
  elenco {
    __typename
    nome
  }
}
    `;
export const ContattiPartsFragmentDoc = gql`
    fragment ContattiParts on Contatti {
  __typename
  indirizzo
  telefono
  email
  piva
  facebook
  instagram
  tiktok
  whatsapp
}
    `;
export const DocentiPartsFragmentDoc = gql`
    fragment DocentiParts on Docenti {
  __typename
  elenco {
    __typename
    nome
    ruolo
    cv
  }
}
    `;
export const PresidenzaPartsFragmentDoc = gql`
    fragment PresidenzaParts on Presidenza {
  __typename
  nome
  ruolo
  bio
}
    `;
export const MissionPartsFragmentDoc = gql`
    fragment MissionParts on Mission {
  __typename
  citazione
  testo
}
    `;
export const SociPartsFragmentDoc = gql`
    fragment SociParts on Soci {
  __typename
  testo
  tesseraTitolo
  tesseraPrezzo
  tesseraTesto
}
    `;
export const DocumentiPartsFragmentDoc = gql`
    fragment DocumentiParts on Documenti {
  __typename
  statuto
  regolamento
  modulo
}
    `;
export const ChiSiamoPartsFragmentDoc = gql`
    fragment ChiSiamoParts on ChiSiamo {
  __typename
  titolo
  stats {
    __typename
    numero
    etichetta
  }
  testo
}
    `;
export const EventiPartsFragmentDoc = gql`
    fragment EventiParts on Eventi {
  __typename
  elenco {
    __typename
    titolo
    testo
  }
}
    `;
export const PremioPartsFragmentDoc = gql`
    fragment PremioParts on Premio {
  __typename
  testo
  alboOro {
    __typename
    nome
  }
}
    `;
export const TestiVariPartsFragmentDoc = gql`
    fragment TestiVariParts on TestiVari {
  __typename
  candidatureTitolo
  candidatureTesto
  trasparenzaTesto
  footerDescrizione
}
    `;
export const GalleriaPartsFragmentDoc = gql`
    fragment GalleriaParts on Galleria {
  __typename
  immagini {
    __typename
    url
    alt
  }
}
    `;
export const HeaderPartsFragmentDoc = gql`
    fragment HeaderParts on Header {
  __typename
  logoMain
  logoSub
  heroEyebrow
  heroTitolo
  heroSottotitolo
  heroDescrizione
}
    `;
export const IniziativePartsFragmentDoc = gql`
    fragment IniziativeParts on Iniziative {
  __typename
  elenco {
    __typename
    testo
    foto
  }
}
    `;
export const CorsiDocument = gql`
    query corsi($relativePath: String!) {
  corsi(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CorsiParts
  }
}
    ${CorsiPartsFragmentDoc}`;
export const CorsiConnectionDocument = gql`
    query corsiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CorsiFilter) {
  corsiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CorsiParts
      }
    }
  }
}
    ${CorsiPartsFragmentDoc}`;
export const ContattiDocument = gql`
    query contatti($relativePath: String!) {
  contatti(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContattiParts
  }
}
    ${ContattiPartsFragmentDoc}`;
export const ContattiConnectionDocument = gql`
    query contattiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContattiFilter) {
  contattiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContattiParts
      }
    }
  }
}
    ${ContattiPartsFragmentDoc}`;
export const DocentiDocument = gql`
    query docenti($relativePath: String!) {
  docenti(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DocentiParts
  }
}
    ${DocentiPartsFragmentDoc}`;
export const DocentiConnectionDocument = gql`
    query docentiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DocentiFilter) {
  docentiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DocentiParts
      }
    }
  }
}
    ${DocentiPartsFragmentDoc}`;
export const PresidenzaDocument = gql`
    query presidenza($relativePath: String!) {
  presidenza(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PresidenzaParts
  }
}
    ${PresidenzaPartsFragmentDoc}`;
export const PresidenzaConnectionDocument = gql`
    query presidenzaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PresidenzaFilter) {
  presidenzaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PresidenzaParts
      }
    }
  }
}
    ${PresidenzaPartsFragmentDoc}`;
export const MissionDocument = gql`
    query mission($relativePath: String!) {
  mission(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MissionParts
  }
}
    ${MissionPartsFragmentDoc}`;
export const MissionConnectionDocument = gql`
    query missionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MissionFilter) {
  missionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MissionParts
      }
    }
  }
}
    ${MissionPartsFragmentDoc}`;
export const SociDocument = gql`
    query soci($relativePath: String!) {
  soci(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SociParts
  }
}
    ${SociPartsFragmentDoc}`;
export const SociConnectionDocument = gql`
    query sociConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SociFilter) {
  sociConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SociParts
      }
    }
  }
}
    ${SociPartsFragmentDoc}`;
export const DocumentiDocument = gql`
    query documenti($relativePath: String!) {
  documenti(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DocumentiParts
  }
}
    ${DocumentiPartsFragmentDoc}`;
export const DocumentiConnectionDocument = gql`
    query documentiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DocumentiFilter) {
  documentiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DocumentiParts
      }
    }
  }
}
    ${DocumentiPartsFragmentDoc}`;
export const ChiSiamoDocument = gql`
    query chiSiamo($relativePath: String!) {
  chiSiamo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ChiSiamoParts
  }
}
    ${ChiSiamoPartsFragmentDoc}`;
export const ChiSiamoConnectionDocument = gql`
    query chiSiamoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ChiSiamoFilter) {
  chiSiamoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ChiSiamoParts
      }
    }
  }
}
    ${ChiSiamoPartsFragmentDoc}`;
export const EventiDocument = gql`
    query eventi($relativePath: String!) {
  eventi(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventiParts
  }
}
    ${EventiPartsFragmentDoc}`;
export const EventiConnectionDocument = gql`
    query eventiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventiFilter) {
  eventiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventiParts
      }
    }
  }
}
    ${EventiPartsFragmentDoc}`;
export const PremioDocument = gql`
    query premio($relativePath: String!) {
  premio(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PremioParts
  }
}
    ${PremioPartsFragmentDoc}`;
export const PremioConnectionDocument = gql`
    query premioConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PremioFilter) {
  premioConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PremioParts
      }
    }
  }
}
    ${PremioPartsFragmentDoc}`;
export const TestiVariDocument = gql`
    query testiVari($relativePath: String!) {
  testiVari(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestiVariParts
  }
}
    ${TestiVariPartsFragmentDoc}`;
export const TestiVariConnectionDocument = gql`
    query testiVariConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestiVariFilter) {
  testiVariConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestiVariParts
      }
    }
  }
}
    ${TestiVariPartsFragmentDoc}`;
export const GalleriaDocument = gql`
    query galleria($relativePath: String!) {
  galleria(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleriaParts
  }
}
    ${GalleriaPartsFragmentDoc}`;
export const GalleriaConnectionDocument = gql`
    query galleriaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleriaFilter) {
  galleriaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleriaParts
      }
    }
  }
}
    ${GalleriaPartsFragmentDoc}`;
export const HeaderDocument = gql`
    query header($relativePath: String!) {
  header(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeaderParts
  }
}
    ${HeaderPartsFragmentDoc}`;
export const HeaderConnectionDocument = gql`
    query headerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeaderFilter) {
  headerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeaderParts
      }
    }
  }
}
    ${HeaderPartsFragmentDoc}`;
export const IniziativeDocument = gql`
    query iniziative($relativePath: String!) {
  iniziative(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IniziativeParts
  }
}
    ${IniziativePartsFragmentDoc}`;
export const IniziativeConnectionDocument = gql`
    query iniziativeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IniziativeFilter) {
  iniziativeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IniziativeParts
      }
    }
  }
}
    ${IniziativePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      corsi(variables: CorsiQueryVariables, options?: C): Promise<{data: CorsiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CorsiQueryVariables, query: string}> {
        return requester<{data: CorsiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CorsiQueryVariables, query: string}, CorsiQueryVariables>(CorsiDocument, variables, options);
      },
    corsiConnection(variables?: CorsiConnectionQueryVariables, options?: C): Promise<{data: CorsiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CorsiConnectionQueryVariables, query: string}> {
        return requester<{data: CorsiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CorsiConnectionQueryVariables, query: string}, CorsiConnectionQueryVariables>(CorsiConnectionDocument, variables, options);
      },
    contatti(variables: ContattiQueryVariables, options?: C): Promise<{data: ContattiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiQueryVariables, query: string}> {
        return requester<{data: ContattiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiQueryVariables, query: string}, ContattiQueryVariables>(ContattiDocument, variables, options);
      },
    contattiConnection(variables?: ContattiConnectionQueryVariables, options?: C): Promise<{data: ContattiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiConnectionQueryVariables, query: string}> {
        return requester<{data: ContattiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiConnectionQueryVariables, query: string}, ContattiConnectionQueryVariables>(ContattiConnectionDocument, variables, options);
      },
    docenti(variables: DocentiQueryVariables, options?: C): Promise<{data: DocentiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocentiQueryVariables, query: string}> {
        return requester<{data: DocentiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocentiQueryVariables, query: string}, DocentiQueryVariables>(DocentiDocument, variables, options);
      },
    docentiConnection(variables?: DocentiConnectionQueryVariables, options?: C): Promise<{data: DocentiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocentiConnectionQueryVariables, query: string}> {
        return requester<{data: DocentiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocentiConnectionQueryVariables, query: string}, DocentiConnectionQueryVariables>(DocentiConnectionDocument, variables, options);
      },
    presidenza(variables: PresidenzaQueryVariables, options?: C): Promise<{data: PresidenzaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PresidenzaQueryVariables, query: string}> {
        return requester<{data: PresidenzaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PresidenzaQueryVariables, query: string}, PresidenzaQueryVariables>(PresidenzaDocument, variables, options);
      },
    presidenzaConnection(variables?: PresidenzaConnectionQueryVariables, options?: C): Promise<{data: PresidenzaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PresidenzaConnectionQueryVariables, query: string}> {
        return requester<{data: PresidenzaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PresidenzaConnectionQueryVariables, query: string}, PresidenzaConnectionQueryVariables>(PresidenzaConnectionDocument, variables, options);
      },
    mission(variables: MissionQueryVariables, options?: C): Promise<{data: MissionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionQueryVariables, query: string}> {
        return requester<{data: MissionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionQueryVariables, query: string}, MissionQueryVariables>(MissionDocument, variables, options);
      },
    missionConnection(variables?: MissionConnectionQueryVariables, options?: C): Promise<{data: MissionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionConnectionQueryVariables, query: string}> {
        return requester<{data: MissionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionConnectionQueryVariables, query: string}, MissionConnectionQueryVariables>(MissionConnectionDocument, variables, options);
      },
    soci(variables: SociQueryVariables, options?: C): Promise<{data: SociQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SociQueryVariables, query: string}> {
        return requester<{data: SociQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SociQueryVariables, query: string}, SociQueryVariables>(SociDocument, variables, options);
      },
    sociConnection(variables?: SociConnectionQueryVariables, options?: C): Promise<{data: SociConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SociConnectionQueryVariables, query: string}> {
        return requester<{data: SociConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SociConnectionQueryVariables, query: string}, SociConnectionQueryVariables>(SociConnectionDocument, variables, options);
      },
    documenti(variables: DocumentiQueryVariables, options?: C): Promise<{data: DocumentiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentiQueryVariables, query: string}> {
        return requester<{data: DocumentiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentiQueryVariables, query: string}, DocumentiQueryVariables>(DocumentiDocument, variables, options);
      },
    documentiConnection(variables?: DocumentiConnectionQueryVariables, options?: C): Promise<{data: DocumentiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentiConnectionQueryVariables, query: string}> {
        return requester<{data: DocumentiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentiConnectionQueryVariables, query: string}, DocumentiConnectionQueryVariables>(DocumentiConnectionDocument, variables, options);
      },
    chiSiamo(variables: ChiSiamoQueryVariables, options?: C): Promise<{data: ChiSiamoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSiamoQueryVariables, query: string}> {
        return requester<{data: ChiSiamoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSiamoQueryVariables, query: string}, ChiSiamoQueryVariables>(ChiSiamoDocument, variables, options);
      },
    chiSiamoConnection(variables?: ChiSiamoConnectionQueryVariables, options?: C): Promise<{data: ChiSiamoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSiamoConnectionQueryVariables, query: string}> {
        return requester<{data: ChiSiamoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSiamoConnectionQueryVariables, query: string}, ChiSiamoConnectionQueryVariables>(ChiSiamoConnectionDocument, variables, options);
      },
    eventi(variables: EventiQueryVariables, options?: C): Promise<{data: EventiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiQueryVariables, query: string}> {
        return requester<{data: EventiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiQueryVariables, query: string}, EventiQueryVariables>(EventiDocument, variables, options);
      },
    eventiConnection(variables?: EventiConnectionQueryVariables, options?: C): Promise<{data: EventiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiConnectionQueryVariables, query: string}> {
        return requester<{data: EventiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiConnectionQueryVariables, query: string}, EventiConnectionQueryVariables>(EventiConnectionDocument, variables, options);
      },
    premio(variables: PremioQueryVariables, options?: C): Promise<{data: PremioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremioQueryVariables, query: string}> {
        return requester<{data: PremioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremioQueryVariables, query: string}, PremioQueryVariables>(PremioDocument, variables, options);
      },
    premioConnection(variables?: PremioConnectionQueryVariables, options?: C): Promise<{data: PremioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremioConnectionQueryVariables, query: string}> {
        return requester<{data: PremioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremioConnectionQueryVariables, query: string}, PremioConnectionQueryVariables>(PremioConnectionDocument, variables, options);
      },
    testiVari(variables: TestiVariQueryVariables, options?: C): Promise<{data: TestiVariQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestiVariQueryVariables, query: string}> {
        return requester<{data: TestiVariQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestiVariQueryVariables, query: string}, TestiVariQueryVariables>(TestiVariDocument, variables, options);
      },
    testiVariConnection(variables?: TestiVariConnectionQueryVariables, options?: C): Promise<{data: TestiVariConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestiVariConnectionQueryVariables, query: string}> {
        return requester<{data: TestiVariConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestiVariConnectionQueryVariables, query: string}, TestiVariConnectionQueryVariables>(TestiVariConnectionDocument, variables, options);
      },
    galleria(variables: GalleriaQueryVariables, options?: C): Promise<{data: GalleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleriaQueryVariables, query: string}> {
        return requester<{data: GalleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleriaQueryVariables, query: string}, GalleriaQueryVariables>(GalleriaDocument, variables, options);
      },
    galleriaConnection(variables?: GalleriaConnectionQueryVariables, options?: C): Promise<{data: GalleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleriaConnectionQueryVariables, query: string}> {
        return requester<{data: GalleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleriaConnectionQueryVariables, query: string}, GalleriaConnectionQueryVariables>(GalleriaConnectionDocument, variables, options);
      },
    header(variables: HeaderQueryVariables, options?: C): Promise<{data: HeaderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderQueryVariables, query: string}> {
        return requester<{data: HeaderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderQueryVariables, query: string}, HeaderQueryVariables>(HeaderDocument, variables, options);
      },
    headerConnection(variables?: HeaderConnectionQueryVariables, options?: C): Promise<{data: HeaderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderConnectionQueryVariables, query: string}> {
        return requester<{data: HeaderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderConnectionQueryVariables, query: string}, HeaderConnectionQueryVariables>(HeaderConnectionDocument, variables, options);
      },
    iniziative(variables: IniziativeQueryVariables, options?: C): Promise<{data: IniziativeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IniziativeQueryVariables, query: string}> {
        return requester<{data: IniziativeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IniziativeQueryVariables, query: string}, IniziativeQueryVariables>(IniziativeDocument, variables, options);
      },
    iniziativeConnection(variables?: IniziativeConnectionQueryVariables, options?: C): Promise<{data: IniziativeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IniziativeConnectionQueryVariables, query: string}> {
        return requester<{data: IniziativeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IniziativeConnectionQueryVariables, query: string}, IniziativeConnectionQueryVariables>(IniziativeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  